const required = require("../middlewares/utility/required");

module.exports = {
    users: {
        register: require("./users/register"),
        login: require("./users/login"),
        wallet: require("./users/createWallet"),
        attemptUnlock: require("./users/attemptUnlock"),
        swap: require("./users/swap"),
        transfer: require("./users/transfer"),
        claim: require("./users/claim.js"),
        unstake: require("./users/unstake.js"),
        issue: require("./users/issue"),
        totalSupply: require("./users/totalSupply"),
        transferFee: require("./users/transferFees"),
        burn: require("./users/burn"),
        vesting1: require("./users/vestingV1"),
        vesting2: require("./users/vestingV2"),
        lockedVestingInfo: require("./users/lockedVestingInfo"),
        issuedTokens: require("./users/issuedTokens"),
        queryWallet: require("./users/queryWallet"),
        queryWalletAdmin: require("./users/queryWalletAdmin"),
        fetchWallets: require("./users/wallets"),
        defaultWallets: require("./users/getDefaultWallets"),
        transactions: require("./users/transactions"),
        stakingInfo: require("./users/stakingInfo"),
        recoverUser: require("./users/recoverUser"),
        resetPassword: require("./users/resetPassword"),
        addAdmin: require("./users/addAdmin"),
        userWallets: require("./users/userWallets"),
        sendMessage: require("./users/sendMessage"),
        createPool: require("./users/createPool"),
        createVote: require("./users/createVote"),
        destroyPool: require("./users/destroyPool"),
        queryPool: require("./users/queryPool"),
        poolHistory: require("./users/poolHistory"),
        getCurrentPhase: require("./users/getCurrentPhase"),
        getCurrentFee: require("./users/getCurrentFee"),
        getPoolConfig: require("./users/poolConfig"),
        updatePoolConfig: require("./users/updatePoolConfig"),
        getBlocks: require("./users/getBlocks"),
        mintToken: require("./users/mintToken"),
        mintBatch: require("./users/mintBatch"),
        burnBatch: require("./users/burnBatch"),
        nftTransfer: require("./users/nftTransfer"),
        nftTransferBatch: require("./users/nftTransferBatch"),
        checkApproval: require("./users/checkApproval"),
        setApproval: require("./users/setApproval"),
        nftBalance: require("./users/nftBalance"),
        nftBalanceBatch: require("./users/nftBalanceBatch"),
        nftTokenInfo: require("./users/getNftTokenInfo"),
        mintedTokens: require("./users/mintedTokens.js"),
        busyNftmint: require("./users/busyNftmint"),
        busyNftTransfer: require("./users/busyNftTransfer"),
        getCurrentOwner: require("./users/getCurrentOwner"),
        updateTokenMetaData: require("./users/updateTokenMetaData"),
        updateSpecialMetaData: require("./users/updateSpecialMetaData"),
        updateTokenIssueFee: require("./users/fees").updateTokenIssueFee,
        updateMessagingFee: require("./users/fees").updateMessagingFee,
        getMessagingFee: require("./users/fees").getMessagingFee,
        getTokenIssueFee: require("./users/fees").getTokenIssueFee,
        getSpecialMintedTokens: require("./users/specialMintedTokens"),
    },

    auth: {
        generateToken: require("./auth/generate-token"),
//        generateTokenAdmin: require("./auth/generate-token-admin"),
        apiKey: require("./auth/apiKey") 
    }
};
